### ISSUE TITLE
App setup example with live reloading and bundling

### ISSUE THREAD

**Issue by dariocravero** [oyyd/react-yue#5]
Hi,

I couldn't get the sample app running and in the process of working out the steps to do so I made a playground to showcase a setup with live reloading + bundling of the app.

If you think it makes sense perhaps we can add that to the README?

https://github.com/viewstools/react-yue-app

Cheers,
Darío

**Comment by shichongrui** [comment]
If you submit a PR I think that would be a good first step. Perhaps just add a small paragraph with a link to your project describing that it demonstrates how to use rollup to do live reloading.

**Comment by dariocravero** [comment]
Done! See the PR above.

It would be nice to combine both setups into a library that makes running these apps easier. The chokidar watcher setup of do-space-client is definitely preferable to nodemon. However, I guess it webpack/rollup hooks could be setup to handle the reloading aspect of it too. `electron-builder` support is another one too which do-space-client seems to have some of it and yackage says it supports it with some limitations but there isn't much detail onto how far it goes -I opened an issue for that https://github.com/yue/yackage/issues/10.

**Comment by shichongrui** [comment]
I agree that having some tool built into react-yue similar to react-native that allows live reloading, hotreloading, CMD-R reloading etc... would be really great. It can be a pain to have to kill `yode` every time one makes a change. Perhaps that an issue could be created to explore ways to accomplish this inside of react-yue.

**Comment by oyyd** [comment]
It seems yackage bundles code in a way that is different from webpack and rollup and it can't bundle react correctly.

I think some features should be supported by yue if possible. But boilerplates for react-yue apps are always welcome.
